### ISSUE TITLE
Scrape bhagavadgItA commentaries as well?

### ISSUE THREAD

**Issue by vvasuki** [cltk/sanskrit_text_gitasupersite#1]
Great work, thanks!

It would be nice if you could similarly scrape all commentaries of bhagavadgItA and dump them in json format..

**Comment by pyaada** [comment]
@vvasuki Can you elaborate?

**Comment by vvasuki** [comment]
Gita supersite offers the following commentaries:
```
 Hindi Translation By Swami Ramsukhdas
Hindi Translation By Swami Tejomayananda
Hindi Translation Of Sri Shankaracharya's Sanskrit Commentary By Sri Harikrishnadas Goenka
Sanskrit Commentary By Sri Shankaracharya
Hindi Commentary By Swami Chinmayananda
Hindi Commentary By Swami Ramsukhdas
Sanskrit Commentary By Sri Abhinavgupta
Sanskrit Commentary By Sri Ramanuja
Sanskrit Commentary By Sri Anandgiri
Sanskrit Commentary By Sri Jayatirtha
Sanskrit Commentary By Sri Madhvacharya
Sanskrit Commentary By Sri Vallabhacharya
Sanskrit Commentary By Sri Madhusudan Saraswati
Sanskrit Commentary By Sri Sridhara Swami
Sanskrit Commentary By Sri Vedantadeshikacharya Venkatanatha
Sanskrit Commentary By Sri Purushottamji
Sanskrit Commentary By Sri Neelkanth
Sanskrit Commentary By Sri Dhanpati
English Commentary By Swami Sivananda
English Translation By Swami Sivananda
English Translation By Purohit Swami
English Translation By Swami Gambirananda
English Translation Of Sri Shankaracharya By Swami Gambirananda
English Translation By Dr. S. Sankaranarayan
English Translation of Abhinavgupta's Sanskrit Commentary By Dr. S. Sankaranarayan
English Translation of Ramanuja's Sanskrit Commentary By Swami Adidevananda
English Translation By Swami Adidevananda 
```
Now, if you could scrape and store all that - and store them as markdown files with YAML frontmatter ( example:  https://github.com/sanskrit/ashtadhyayi presented in https://ashtadhyayi.github.io/ui/?sutra=1.4.24  ), this data can be presented in a variety of other formats for the benefit of connoiseurs.

**Comment by pyaada** [comment]
> Gita supersite offers the following commentaries:
> 
> ```
>  Hindi Translation By Swami Ramsukhdas
> Hindi Translation By Swami Tejomayananda
> Hindi Translation Of Sri Shankaracharya's Sanskrit Commentary By Sri Harikrishnadas Goenka
> Sanskrit Commentary By Sri Shankaracharya
> Hindi Commentary By Swami Chinmayananda
> Hindi Commentary By Swami Ramsukhdas
> Sanskrit Commentary By Sri Abhinavgupta
> Sanskrit Commentary By Sri Ramanuja
> Sanskrit Commentary By Sri Anandgiri
> Sanskrit Commentary By Sri Jayatirtha
> Sanskrit Commentary By Sri Madhvacharya
> Sanskrit Commentary By Sri Vallabhacharya
> Sanskrit Commentary By Sri Madhusudan Saraswati
> Sanskrit Commentary By Sri Sridhara Swami
> Sanskrit Commentary By Sri Vedantadeshikacharya Venkatanatha
> Sanskrit Commentary By Sri Purushottamji
> Sanskrit Commentary By Sri Neelkanth
> Sanskrit Commentary By Sri Dhanpati
> English Commentary By Swami Sivananda
> English Translation By Swami Sivananda
> English Translation By Purohit Swami
> English Translation By Swami Gambirananda
> English Translation Of Sri Shankaracharya By Swami Gambirananda
> English Translation By Dr. S. Sankaranarayan
> English Translation of Abhinavgupta's Sanskrit Commentary By Dr. S. Sankaranarayan
> English Translation of Ramanuja's Sanskrit Commentary By Swami Adidevananda
> English Translation By Swami Adidevananda 
> ```
> Now, if you could scrape and store all that - and store them as markdown files with YAML frontmatter ( example: https://github.com/sanskrit/ashtadhyayi presented in https://ashtadhyayi.github.io/ui/?sutra=1.4.24 ), this data can be presented in a variety of other formats for the benefit of connoiseurs.

Do you know of licence free links to these commentaries?

**Comment by vvasuki** [comment]
No - Just whatever is available at [gitasupersite](https://www.gitasupersite.iitk.ac.in/srimad?language=dv&field_chapter_value=1&field_nsutra_value=1&htrskd=1&httyn=1&htshg=1&scsh=1&hcchi=1&hcrskd=1&scang=1&scram=1&scanand=1&scjaya=1&scmad=1&scval=1&scms=1&scsri=1&scvv=1&scpur=1&scneel=1&scdhan=1&ecsiva=1&etsiva=1&etpurohit=1&etgb=1&setgb=1&etssa=1&etassa=1&etradi=1&etadi=1).
